version: 1
policy:
  pullRequests: public
tasks:
  $flattenDeep:
    - $if: tasks_for == "github-push"
      then:
        $map:
          $flatten:
            $match: {
              True: [
                {name: firefox, channel: nightly},
                {name: chrome, channel: dev},
                {name: firefox, channel: stable},
                {name: chrome, channel: stable}
              ],
              event.ref == "refs/heads/master": [{name: firefox, channel: nightly}, {name: chrome, channel: dev}],
              event.ref == "refs/heads/epochs/daily": [{name: firefox, channel: stable}, {name: chrome, channel: stable}],
              event.ref == "refs/heads/epochs/weekly": [{name: firefox, channel: beta}, {name: chrome, channel: beta}]
              }
        each(browser):
          $map:
            - [placeholder, 1, 20]
            - [placeholder, 2, 20]
            - [placeholder, 3, 20]
            - [placeholder, 4, 20]
            - [placeholder, 5, 20]
            - [placeholder, 6, 20]
            - [placeholder, 7, 20]
            - [placeholder, 8, 20]
            - [placeholder, 9, 20]
            - [placeholder, 10, 20]
            - [placeholder, 11, 20]
            - [placeholder, 12, 20]
            - [placeholder, 13, 20]
            - [placeholder, 14, 20]
            - [placeholder, 15, 20]
            - [placeholder, 16, 20]
            - [placeholder, 17, 20]
            - [placeholder, 18, 20]
            - [placeholder, 19, 20]
            - [placeholder, 20, 20]
          each(chunk):
            taskId: {$eval: 'as_slugid(browser.name + browser.channel + chunk[0] + str(chunk[1]))'}
            taskGroupId: {$eval: 'as_slugid("task group")'}
            created: {$fromNow: ''}
            deadline: {$fromNow: '24 hours'}
            provisionerId: aws-provisioner-v1
            workerType:
              $if: event.repository.full_name == 'web-platform-tests/wpt'
              then:
                wpt-docker-worker
              else:
                github-worker
            metadata:
              name: wpt-${browser.name}-${browser.channel}-${chunk[0]}-${chunk[1]}
              description: >-
                A subset of WPT's "${chunk[0]}" tests (chunk number ${chunk[1]}
                of ${chunk[2]}), run in the ${browser.channel} release of
                ${browser.name}.
              owner: ${event.pusher.email}
              source: ${event.repository.url}
            payload:
              image: harjgam/web-platform-tests:0.22
              maxRunTime: 7200
              artifacts:
                public/results:
                  path: /home/test/artifacts
                  type: directory
              command:
                - /bin/bash
                - --login
                - -c
                - set -ex;
                  ~/start.sh
                    ${event.repository.url}
                    ${event.ref}
                    ${event.after}
                    ${browser.name}
                    ${browser.channel};
                  cd ~/web-platform-tests;
                  wget
                    https://github.com/web-platform-tests/wpt/releases/download/merge_pr_10137/MANIFEST-98103d8c3ecbcab364bc0dc86fa176ec673b56d8.json.gz
                    --output-document MANIFEST.json.gz;
                  gunzip MANIFEST.json.gz;
                  ./tools/ci/taskcluster-run.py
                    ${browser.name}
                    --
                    --channel=${browser.channel}
                    --log-wptreport=../artifacts/wpt_report.json
                    --no-fail-on-unexpected
                    --this-chunk=${chunk[1]}
                    --total-chunks=${chunk[2]};
    - $if: tasks_for == "github-pull-request"
      then:
        # Taskcluster responds to a number of events issued by the GitHub API
        # which should not trigger re-validation.
        $if: event.action in ['opened', 'reopened', 'synchronize']
        then:
          $map: [{name: firefox, channel: nightly}, {name: chrome, channel: dev}]
          each(browser):
            $map:
              - name: wpt-${browser.name}-${browser.channel}-stability
                description: >-
                  Verify that all tests affected by a pull request are stable
                  when executed in ${browser.name}.
                extra_args: '--verify'
              - name: wpt-${browser.name}-${browser.channel}-results
                description: >-
                  Collect results for all tests affected by a pull request in
                  ${browser.name}.
                extra_args: '--no-fail-on-unexpected --log-wptreport=../artifacts/wpt_report.json'
            each(operation):
              taskId: {$eval: 'as_slugid(operation.name)'}
              taskGroupId: {$eval: 'as_slugid("task group")'}
              created: {$fromNow: ''}
              deadline: {$fromNow: '24 hours'}
              provisionerId: aws-provisioner-v1
              workerType:
                $if: event.repository.full_name == 'web-platform-tests/wpt'
                then:
                  wpt-docker-worker
                else:
                  github-worker
              metadata:
                name: ${operation.name}
                description: ${operation.description}
                owner: ${event.pull_request.user.login}@users.noreply.github.com
                source: ${event.repository.url}
              payload:
                image: harjgam/web-platform-tests:0.22
                maxRunTime: 7200
                artifacts:
                  public/results:
                    path: /home/test/artifacts
                    type: directory
                # Fetch the GitHub-provided merge commit (rather than the pull
                # request branch) so that the tasks simulate the behavior of the
                # submitted patch after it is merged. Using the merge commit also
                # simplifies detection of modified files because the first parent
                # of the merge commit can consistently be used to summarize the
                # changes.
                command:
                  - /bin/bash
                  - --login
                  - -c
                  - set -ex;
                    ~/start.sh
                      ${event.repository.clone_url}
                      refs/pull/${event.number}/merge
                      FETCH_HEAD
                      ${browser.name}
                      ${browser.channel};
                    cd ~/web-platform-tests;
                    ./tools/ci/taskcluster-run.py
                      --commit-range HEAD^
                      ${browser.name}
                      --
                      --channel=${browser.channel}
                      ${operation.extra_args};
